### PR TITLE
Convert Travis CI config to GitHub Actions

### PR DESCRIPTION
**Pull request by mbrukman**
Travis CI dependency installation and tests are ported as-is. Travis CI had an
unspecified execution environment; in GitHub Actions, we will run on available
Ubuntu (18.04 and 20.04) and macOS (10.15 and 11) versions.

Additionally Travis CI config has not been updated in a while and only ran with
Python 2.7, 3.3, and 3.4; for GitHub Actions, this commit adds all newer Python
versions (up to 3.10) as well.

Update README.md to use the new GitHub Actions badge and point to the new test
status, which will become active as soon as this PR goes through the testing
process the first time.

Closes https://github.com/rossant/ipycache/issues/52

### CODE REVIEW

**Comment by mbrukman** [comment]
@rossant — looks like GitHub Actions are not enabled on this repo, and I do not have permissions to enable them. Can you please visit https://github.com/rossant/ipycache/settings/actions and enable "Allow all actions"?

For "Workflow permissions", you can select "Read repository contents permission" since these workflows don't need to write to the repository.

You may also have to allow GitHub Actions manually to run on this PR as well.

Thanks!

**Comment by rossant** [comment]
OK. All good?
image

**Review by rossant — APPROVED** [review]

**Comment by mbrukman** [comment]
@rossant — the workflow still doesn't appear to have run, even after I force-pushed my branch again after your approval.

I saw you approved the PR, but did you get a prompt in the review UI to approve the _workflow_ itself? There should be another button in the UI, see [these docs](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) and the UI should look something like this:

image

**Comment by rossant** [comment]
I don't think I'm seeing this?

image

**Comment by mbrukman** [comment]
OK, maybe it just doesn't run on first creation of the GitHub Actions config from a PR from an external contributor (non-owner of the repo)? That may be a corner case, and I haven't seen this issue before, but I was usually the maintainer of the repo when I was adding the initial Travis CI or GitHub Actions config, so maybe it's a safety mechanism in that case.

I'll merge this PR given your approval, and let's see if it triggers for future PRs, at which point we can adjust and fix the config as necessary. In any case, Travis CI hasn't been running on this repo for a while, so we're not losing anything.

**Pull request merged**
